/**
 * AlterValue v3.0 - BNQ 9700-800 Requirements Data
 * 
 * Exigences détaillées de la norme CAN/BNQ 9700-800/2020
 * Chapitres 5-9 avec mapping vers les documents et workflows
 */

import { BnqLevel } from '@prisma/client';

export interface BnqRequirementData {
  chapter: number;
  section: string;
  title: string;
  description: string;
  requirement: string;
  requiredForLevel: BnqLevel;
  isOptional: boolean;
  category: string;
  linkedDocumentCode?: string;
  linkedWorkflowStep?: string;
  verificationMethod?: string;
  evidence?: string;
  frequency?: string;
  sortOrder: number;
}

// Activity Sphere labels for display
export const ACTIVITY_SPHERE_LABELS = {
  HABITUDES_VIE: {
    name: 'Habitudes de vie',
    description: 'Nutrition, activité physique, tabagisme, gestion du stress, sommeil, alcool/drogues',
    icon: 'Heart',
    color: 'bg-green-500',
  },
  CONCILIATION_TRAVAIL: {
    name: 'Conciliation travail-vie personnelle',
    description: 'Horaires flexibles, télétravail, congés, banques de temps, semaine réduite',
    icon: 'Scale',
    color: 'bg-blue-500',
  },
  ENVIRONNEMENT_TRAVAIL: {
    name: 'Environnement de travail',
    description: 'Ergonomie, éclairage, bruit, salubrité, équipements, facteurs de risque SST',
    icon: 'Building2',
    color: 'bg-amber-500',
  },
  PRATIQUES_GESTION: {
    name: 'Pratiques de gestion',
    description: '8 éléments: harcèlement, reconnaissance, autonomie, charge travail, soutien, justice/équité, compétences, information',
    icon: 'Users',
    color: 'bg-purple-500',
  },
};

// Minimum requirements per certification level
export const BNQ_LEVEL_REQUIREMENTS = {
  ES: {
    minPriorities: 1,
    minInterventions: 2,
    minPratiquesGestion: 0,
    dataCollectionFrequency: '3 ans',
    adminDataFrequency: 'occasionnel',
  },
  ESE: {
    minPriorities: 2,
    minInterventions: 4,
    minPratiquesGestion: 1,
    dataCollectionFrequency: '2-3 ans',
    adminDataFrequency: 'occasionnel',
  },
  ESE_PLUS: {
    minPriorities: 3,
    minInterventions: 6,
    minPratiquesGestion: 2,
    dataCollectionFrequency: '2-3 ans',
    adminDataFrequency: 'annuel',
  },
};

// Priority level labels
export const PRIORITY_LABELS = {
  LOW: { name: 'Basse', color: 'bg-gray-400' },
  MEDIUM: { name: 'Moyenne', color: 'bg-blue-500' },
  HIGH: { name: 'Haute', color: 'bg-orange-500' },
  CRITICAL: { name: 'Critique', color: 'bg-red-500' },
};

// Intervention status labels
export const INTERVENTION_STATUS_LABELS = {
  PLANNED: { name: 'Planifiée', color: 'bg-slate-500' },
  IN_PROGRESS: { name: 'En cours', color: 'bg-blue-500' },
  COMPLETED: { name: 'Terminée', color: 'bg-green-500' },
  CANCELLED: { name: 'Annulée', color: 'bg-red-500' },
  POSTPONED: { name: 'Reportée', color: 'bg-amber-500' },
};

// Alert type labels
export const ALERT_TYPE_LABELS = {
  DOCUMENT_EXPIRY: { name: 'Expiration document', icon: 'FileWarning' },
  DOCUMENT_MISSING: { name: 'Document manquant', icon: 'FileMinus' },
  DOCUMENT_REVISION: { name: 'Révision requise', icon: 'FileEdit' },
  WORKFLOW_OVERDUE: { name: 'Étape en retard', icon: 'ClipboardX' },
  INTERVENTION_DEADLINE: { name: 'Échéance intervention', icon: 'Calendar' },
  INTERVENTION_OVERDUE: { name: 'Intervention en retard', icon: 'AlertTriangle' },
  DATA_COLLECTION: { name: 'Collecte de données', icon: 'Database' },
  ANNUAL_REVIEW: { name: 'Revue annuelle', icon: 'CalendarDays' },
  CERTIFICATION_EXPIRY: { name: 'Certification', icon: 'Award' },
  DUERP_UPDATE: { name: 'MAJ DUERP', icon: 'ShieldAlert' },
  COMMITTEE_MEETING: { name: 'Réunion comité', icon: 'Users' },
  CUSTOM: { name: 'Personnalisé', icon: 'Bell' },
};

// Alert severity labels
export const ALERT_SEVERITY_LABELS = {
  INFO: { name: 'Information', color: 'bg-blue-100 text-blue-800', icon: 'Info' },
  WARNING: { name: 'Attention', color: 'bg-amber-100 text-amber-800', icon: 'AlertTriangle' },
  URGENT: { name: 'Urgent', color: 'bg-orange-100 text-orange-800', icon: 'AlertCircle' },
  CRITICAL: { name: 'Critique', color: 'bg-red-100 text-red-800', icon: 'XCircle' },
};

// BNQ Requirements data - Chapitres 5-9
export const BNQ_REQUIREMENTS: BnqRequirementData[] = [
  // =====================================================
  // CHAPITRE 5 - ENGAGEMENT DE LA DIRECTION
  // =====================================================
  {
    chapter: 5,
    section: '5.1',
    title: 'Engagement formel de la direction',
    description: "La haute direction doit s'engager formellement envers la démarche",
    requirement: "La haute direction doit démontrer son engagement envers la démarche de santé et mieux-être par un engagement formel écrit et signé.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Engagement Direction',
    linkedDocumentCode: 'NOTE_INTENTION',
    linkedWorkflowStep: 'ENGAGEMENT_INITIAL',
    verificationMethod: 'Document signé et daté',
    evidence: "Note d'intention ou lettre d'engagement signée",
    frequency: 'Initial + si changement direction',
    sortOrder: 1,
  },
  {
    chapter: 5,
    section: '5.2',
    title: 'Politique santé et mieux-être',
    description: 'Politique officielle approuvée par la direction',
    requirement: "L'organisation doit établir une politique de santé et mieux-être approuvée par la haute direction, communiquée au personnel et révisée périodiquement.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Engagement Direction',
    linkedDocumentCode: 'POLITIQUE_SME',
    linkedWorkflowStep: 'POLITIQUE_SME',
    verificationMethod: 'Document approuvé et preuve de communication',
    evidence: 'Politique signée + PV approbation + preuve communication',
    frequency: '3 ans',
    sortOrder: 2,
  },
  {
    chapter: 5,
    section: '5.2.a',
    title: 'Affichage de la politique (EsE)',
    description: 'La politique doit être affichée de façon visible',
    requirement: "Pour le niveau [EsE], la politique de santé et mieux-être doit être affichée de façon visible dans l'organisation.",
    requiredForLevel: 'ESE',
    isOptional: true,
    category: 'Engagement Direction',
    linkedDocumentCode: 'POLITIQUE_SME',
    verificationMethod: 'Photo ou attestation affichage',
    evidence: "Preuve d'affichage visible",
    frequency: 'Continu',
    sortOrder: 3,
  },
  {
    chapter: 5,
    section: '5.3',
    title: 'Approche préventive SST',
    description: 'Approche préventive en santé et sécurité au travail',
    requirement: "L'organisation doit intégrer une approche préventive en santé et sécurité au travail dans sa démarche.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'SST',
    linkedDocumentCode: 'PROGRAMME_PREVENTION',
    verificationMethod: 'Programme de prévention documenté',
    evidence: 'Programme SST + preuves de mise en œuvre',
    frequency: 'Annuel',
    sortOrder: 4,
  },
  {
    chapter: 5,
    section: '5.3.1',
    title: 'Identification et contrôle des risques',
    description: 'Méthode documentée pour identifier et contrôler les risques',
    requirement: "L'organisation doit utiliser une méthode documentée pour l'identification et le contrôle des risques pour la santé et sécurité.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'SST',
    linkedDocumentCode: 'DUERP',
    linkedWorkflowStep: 'DOCUMENTS_SST',
    verificationMethod: 'DUERP à jour',
    evidence: 'Document Unique d\'Évaluation des Risques Professionnels',
    frequency: 'Annuel',
    sortOrder: 5,
  },
  {
    chapter: 5,
    section: '5.4.a',
    title: 'Procédure de retour au travail',
    description: 'Accompagnement pour le retour au travail après absence',
    requirement: "L'organisation doit avoir une procédure d'accompagnement pour le retour au travail après une absence prolongée.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Mesures RH',
    linkedDocumentCode: 'PROCEDURE_RETOUR',
    verificationMethod: 'Procédure documentée',
    evidence: 'Document procédure + preuves application',
    frequency: '3 ans',
    sortOrder: 6,
  },
  {
    chapter: 5,
    section: '5.4.b',
    title: 'Procédure de maintien au travail (EsE+)',
    description: 'Maintien en emploi pour capacité réduite',
    requirement: "Pour le niveau [EsE+], l'organisation doit avoir une procédure de maintien en emploi pour les personnes à capacité réduite.",
    requiredForLevel: 'ESE_PLUS',
    isOptional: true,
    category: 'Mesures RH',
    linkedDocumentCode: 'PROCEDURE_MAINTIEN',
    verificationMethod: 'Procédure documentée',
    evidence: 'Document procédure + cas appliqués',
    frequency: '3 ans',
    sortOrder: 7,
  },
  {
    chapter: 5,
    section: '5.5.1',
    title: 'Représentant de la direction',
    description: 'Nomination d\'un représentant de la direction',
    requirement: "La direction doit nommer un représentant responsable de la démarche santé mieux-être.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Engagement Direction',
    linkedDocumentCode: 'NOMINATION_REPRESENTANT',
    linkedWorkflowStep: 'ENGAGEMENT_INITIAL',
    verificationMethod: 'Document de nomination',
    evidence: 'Lettre de nomination + organigramme',
    frequency: 'Si changement',
    sortOrder: 8,
  },
  {
    chapter: 5,
    section: '5.6',
    title: 'Ressources et temps',
    description: 'Allocation de ressources pour la démarche',
    requirement: "L'organisation doit allouer les ressources humaines, financières et matérielles nécessaires à la démarche.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Engagement Direction',
    verificationMethod: 'Budget alloué + temps dédié',
    evidence: 'Preuve budget + temps comité',
    frequency: 'Annuel',
    sortOrder: 9,
  },
  {
    chapter: 5,
    section: '5.7',
    title: 'Rôle des gestionnaires (EsE)',
    description: 'Intégration du volet santé dans les tâches des gestionnaires',
    requirement: "Pour le niveau [EsE], le volet santé mieux-être doit être intégré dans les descriptions de tâches des gestionnaires.",
    requiredForLevel: 'ESE',
    isOptional: true,
    category: 'Mesures RH',
    linkedDocumentCode: 'DESC_TACHES_GESTIONNAIRES',
    verificationMethod: 'Descriptions de postes',
    evidence: 'Fiches de poste avec volet santé',
    frequency: 'Si modification',
    sortOrder: 10,
  },
  
  // =====================================================
  // CHAPITRE 6 - COMITÉ SANTÉ ET MIEUX-ÊTRE
  // =====================================================
  {
    chapter: 6,
    section: '6.1',
    title: 'Constitution du comité',
    description: 'Comité santé mieux-être représentatif',
    requirement: "L'organisation doit constituer un comité santé et mieux-être représentatif de l'ensemble du personnel (minimum 4 membres).",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Comité',
    linkedDocumentCode: 'LISTE_MEMBRES_COMITE',
    linkedWorkflowStep: 'MISE_EN_PLACE_COMITE',
    verificationMethod: 'Liste des membres + organigramme',
    evidence: 'Liste membres avec fonctions',
    frequency: 'Annuel',
    sortOrder: 20,
  },
  {
    chapter: 6,
    section: '6.2',
    title: 'Mandat du comité',
    description: 'Mandat et objectifs définis',
    requirement: "Le comité doit avoir un mandat clairement défini avec des objectifs mesurables.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Comité',
    linkedDocumentCode: 'MANDAT_COMITE',
    linkedWorkflowStep: 'MISE_EN_PLACE_COMITE',
    verificationMethod: 'Document de mandat',
    evidence: 'Charte du comité + objectifs',
    frequency: '3 ans',
    sortOrder: 21,
  },
  {
    chapter: 6,
    section: '6.3',
    title: 'Réunions du comité',
    description: 'Minimum 4 réunions par an',
    requirement: "Le comité doit se réunir au minimum 4 fois par année et documenter ses réunions.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Comité',
    linkedDocumentCode: 'CR_REUNIONS_COMITE',
    verificationMethod: 'Comptes-rendus de réunions',
    evidence: 'PV de réunions (min 4/an)',
    frequency: 'Continu',
    sortOrder: 22,
  },
  {
    chapter: 6,
    section: '6.4',
    title: 'Communication liste membres',
    description: 'Liste des membres communiquée au personnel',
    requirement: "La liste des membres du comité doit être communiquée à l'ensemble du personnel.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Comité',
    linkedWorkflowStep: 'MISE_EN_PLACE_COMITE',
    verificationMethod: 'Preuve de communication',
    evidence: 'Email, affichage ou intranet',
    frequency: 'Annuel',
    sortOrder: 23,
  },
  
  // =====================================================
  // CHAPITRE 7 - COLLECTE ET ANALYSE DES DONNÉES
  // =====================================================
  {
    chapter: 7,
    section: '7.1',
    title: 'Identification des besoins',
    description: 'Identifier les besoins prioritaires du personnel',
    requirement: "L'organisation doit collecter des données pour identifier les besoins prioritaires du personnel en matière de santé et mieux-être.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Collecte données',
    linkedDocumentCode: 'RAPPORT_COLLECTE_PERSONNEL',
    verificationMethod: 'Rapport de collecte',
    evidence: 'Questionnaire + analyse résultats',
    frequency: '2-3 ans',
    sortOrder: 30,
  },
  {
    chapter: 7,
    section: '7.2',
    title: 'Confidentialité des données',
    description: 'Mesures de confidentialité écrites',
    requirement: "L'organisation doit avoir des mesures de confidentialité écrites pour la protection des données personnelles collectées.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Confidentialité',
    linkedDocumentCode: 'MESURES_CONFIDENTIALITE',
    linkedWorkflowStep: 'CONFIDENTIALITE_RGPD',
    verificationMethod: 'Document mesures',
    evidence: 'Politique confidentialité + procédures',
    frequency: '3 ans',
    sortOrder: 31,
  },
  {
    chapter: 7,
    section: '7.2.a',
    title: 'Consentement éclairé',
    description: 'Consentement pour la collecte de données',
    requirement: "L'organisation doit obtenir le consentement éclairé des participants pour la collecte de données.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Confidentialité',
    linkedDocumentCode: 'CONSENTEMENT_COLLECTE',
    linkedWorkflowStep: 'CONFIDENTIALITE_RGPD',
    verificationMethod: 'Formulaire de consentement',
    evidence: 'Modèle de formulaire utilisé',
    frequency: 'Par collecte',
    sortOrder: 32,
  },
  {
    chapter: 7,
    section: '7.3',
    title: 'Calendrier de collecte',
    description: 'Collecte périodique des données',
    requirement: "Les données auprès du personnel doivent être collectées selon un calendrier défini (aux 2-3 ans minimum).",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Collecte données',
    verificationMethod: 'Calendrier + historique',
    evidence: 'Dates des collectes effectuées',
    frequency: '2-3 ans',
    sortOrder: 33,
  },
  {
    chapter: 7,
    section: '7.4.1',
    title: 'Couverture des 4 sphères',
    description: 'Collecte sur les 4 sphères d\'activité',
    requirement: "La collecte de données doit couvrir les 4 sphères d'activité: habitudes de vie, conciliation travail-vie, environnement de travail, pratiques de gestion.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Collecte données',
    verificationMethod: 'Questionnaire couvrant 4 sphères',
    evidence: 'Questions pour chaque sphère',
    frequency: '2-3 ans',
    sortOrder: 34,
  },
  {
    chapter: 7,
    section: '7.4.2.d',
    title: 'Pratiques de gestion - 8 éléments',
    description: 'Évaluation des 8 éléments de pratiques de gestion',
    requirement: "Pour la sphère pratiques de gestion, les 8 éléments suivants doivent être évalués: harcèlement, reconnaissance, autonomie, charge de travail, soutien, justice/équité, développement compétences, information.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Collecte données',
    verificationMethod: 'Questions sur 8 éléments',
    evidence: 'Questionnaire avec 8 dimensions',
    frequency: '2-3 ans',
    sortOrder: 35,
  },
  {
    chapter: 7,
    section: '7.4.3',
    title: 'Fréquence du présentéisme',
    description: 'Mesure de la fréquence du présentéisme',
    requirement: "La collecte doit inclure une mesure de la fréquence du présentéisme.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Collecte données',
    verificationMethod: 'Question présentéisme',
    evidence: 'Enquête Méthode B AlterValue',
    frequency: '2-3 ans',
    sortOrder: 36,
  },
  {
    chapter: 7,
    section: '7.4.5',
    title: 'Données administratives',
    description: 'Collecte des données administratives',
    requirement: "L'organisation doit collecter des données administratives pertinentes.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Données admin',
    linkedDocumentCode: 'RAPPORT_DONNEES_ADMIN',
    verificationMethod: 'Rapport données admin',
    evidence: 'Indicateurs compilés',
    frequency: 'Annuel (EsE+)',
    sortOrder: 37,
  },
  {
    chapter: 7,
    section: '7.4.5.a',
    title: 'Cotisations accidents travail',
    description: 'Suivi des cotisations CNESST/accidents',
    requirement: "Les cotisations pour accidents du travail doivent être suivies.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Données admin',
    verificationMethod: 'Relevé cotisations',
    evidence: 'Cotisations CNESST ou équivalent',
    frequency: 'Annuel',
    sortOrder: 38,
  },
  {
    chapter: 7,
    section: '7.4.5.b',
    title: 'Coût assurances collectives',
    description: 'Suivi des coûts d\'assurances',
    requirement: "Les coûts des assurances collectives doivent être suivis.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Données admin',
    verificationMethod: 'Relevé assurances',
    evidence: 'Coûts assurances annuels',
    frequency: 'Annuel',
    sortOrder: 39,
  },
  {
    chapter: 7,
    section: '7.4.5.e',
    title: 'Taux d\'absentéisme et coût',
    description: 'Taux et coût de l\'absentéisme',
    requirement: "Le taux d'absentéisme et son coût doivent être mesurés.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Données admin',
    verificationMethod: 'Indicateurs AlterValue',
    evidence: 'Données KPI AlterValue',
    frequency: 'Annuel',
    sortOrder: 40,
  },
  {
    chapter: 7,
    section: '7.4.5.f',
    title: 'Taux de roulement',
    description: 'Taux de roulement du personnel',
    requirement: "Le taux de roulement du personnel doit être mesuré.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Données admin',
    verificationMethod: 'Indicateur roulement',
    evidence: 'Données RH',
    frequency: 'Annuel',
    sortOrder: 41,
  },
  {
    chapter: 7,
    section: '7.4.5.g',
    title: 'Utilisation PAE',
    description: 'Données d\'utilisation du PAE',
    requirement: "Les données d'utilisation du Programme d'aide aux employés (PAE) doivent être suivies.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Données admin',
    verificationMethod: 'Rapport PAE',
    evidence: 'Statistiques utilisation PAE',
    frequency: 'Annuel',
    sortOrder: 42,
  },
  {
    chapter: 7,
    section: '7.4.5.h',
    title: 'Registre accidents travail (EsE+)',
    description: 'Registre des accidents du travail',
    requirement: "Pour le niveau [EsE+], un registre des accidents du travail et maladies professionnelles doit être tenu.",
    requiredForLevel: 'ESE_PLUS',
    isOptional: true,
    category: 'Données admin',
    linkedDocumentCode: 'REGISTRE_ACCIDENTS',
    verificationMethod: 'Registre à jour',
    evidence: 'Registre accidents/incidents',
    frequency: 'Continu',
    sortOrder: 43,
  },
  {
    chapter: 7,
    section: '7.5.1',
    title: 'Rapport de collecte',
    description: 'Rapport synthèse des données collectées',
    requirement: "Un rapport synthétisant les données collectées doit être produit.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Rapports',
    linkedDocumentCode: 'RAPPORT_COLLECTE_PERSONNEL',
    verificationMethod: 'Rapport disponible',
    evidence: 'Rapport de synthèse',
    frequency: '2-3 ans',
    sortOrder: 44,
  },
  
  // =====================================================
  // CHAPITRE 8 - PLAN D'ACTION ET INTERVENTIONS
  // =====================================================
  {
    chapter: 8,
    section: '8.1',
    title: 'Plan d\'action annuel',
    description: 'Plan d\'action santé mieux-être',
    requirement: "L'organisation doit établir un plan d'action annuel en santé et mieux-être basé sur les besoins identifiés.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Plan action',
    linkedDocumentCode: 'PLAN_ACTION_SME',
    verificationMethod: 'Plan documenté',
    evidence: 'Plan d\'action annuel',
    frequency: 'Annuel',
    sortOrder: 50,
  },
  {
    chapter: 8,
    section: '8.2',
    title: 'Besoins prioritaires adressés',
    description: 'Interventions répondant aux besoins prioritaires',
    requirement: "Le plan d'action doit inclure des interventions répondant aux besoins prioritaires identifiés lors de la collecte.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Plan action',
    verificationMethod: 'Lien collecte → interventions',
    evidence: 'Justification des interventions',
    frequency: 'Annuel',
    sortOrder: 51,
  },
  {
    chapter: 8,
    section: '8.3',
    title: 'Minimum d\'interventions',
    description: 'Nombre minimum d\'interventions selon niveau',
    requirement: "Le plan doit inclure un minimum d'interventions: [Es]: 2, [EsE]: 4, [EsE+]: 6 interventions.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Plan action',
    verificationMethod: 'Comptage interventions',
    evidence: 'Liste interventions dans le plan',
    frequency: 'Annuel',
    sortOrder: 52,
  },
  {
    chapter: 8,
    section: '8.4',
    title: 'Pratiques de gestion incluses (EsE)',
    description: 'Interventions sur les pratiques de gestion',
    requirement: "Pour [EsE], au moins 1 intervention doit porter sur les pratiques de gestion. Pour [EsE+], au moins 2.",
    requiredForLevel: 'ESE',
    isOptional: true,
    category: 'Plan action',
    verificationMethod: 'Interventions par sphère',
    evidence: 'Interventions pratiques gestion',
    frequency: 'Annuel',
    sortOrder: 53,
  },
  {
    chapter: 8,
    section: '8.5',
    title: 'Responsables et échéances',
    description: 'Interventions avec responsables et échéances',
    requirement: "Chaque intervention doit avoir un responsable identifié et une échéance définie.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Plan action',
    verificationMethod: 'Plan détaillé',
    evidence: 'Responsables + dates cibles',
    frequency: 'Annuel',
    sortOrder: 54,
  },
  {
    chapter: 8,
    section: '8.6',
    title: 'Objectifs mesurables',
    description: 'Objectifs mesurables pour chaque intervention',
    requirement: "Chaque intervention doit avoir des objectifs mesurables permettant d'évaluer son efficacité.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Plan action',
    verificationMethod: 'Indicateurs définis',
    evidence: 'KPIs par intervention',
    frequency: 'Annuel',
    sortOrder: 55,
  },
  
  // =====================================================
  // CHAPITRE 9 - ÉVALUATION ET AMÉLIORATION CONTINUE
  // =====================================================
  {
    chapter: 9,
    section: '9.1',
    title: 'Évaluation des interventions',
    description: 'Évaluation de l\'efficacité des interventions',
    requirement: "L'organisation doit évaluer l'efficacité de chaque intervention réalisée.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Évaluation',
    verificationMethod: 'Rapports d\'évaluation',
    evidence: 'Résultats par intervention',
    frequency: 'Après chaque intervention',
    sortOrder: 60,
  },
  {
    chapter: 9,
    section: '9.2',
    title: 'Taux de participation',
    description: 'Mesure de la participation aux interventions',
    requirement: "Le taux de participation à chaque intervention doit être mesuré.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Évaluation',
    verificationMethod: 'Statistiques participation',
    evidence: 'Données de participation',
    frequency: 'Par intervention',
    sortOrder: 61,
  },
  {
    chapter: 9,
    section: '9.3',
    title: 'Satisfaction des participants',
    description: 'Évaluation de la satisfaction',
    requirement: "La satisfaction des participants à chaque intervention doit être évaluée.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Évaluation',
    verificationMethod: 'Sondages satisfaction',
    evidence: 'Score satisfaction',
    frequency: 'Par intervention',
    sortOrder: 62,
  },
  {
    chapter: 9,
    section: '9.3.2',
    title: 'Rapport synthèse annuel',
    description: 'Rapport annuel de la démarche',
    requirement: "Un rapport synthèse annuel de la démarche santé mieux-être doit être produit.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Rapports',
    linkedDocumentCode: 'RAPPORT_SYNTHESE_ANNUEL',
    verificationMethod: 'Rapport annuel',
    evidence: 'Rapport de synthèse',
    frequency: 'Annuel',
    sortOrder: 63,
  },
  {
    chapter: 9,
    section: '9.4',
    title: 'Revue annuelle de la démarche (EsE)',
    description: 'Revue formelle de la démarche',
    requirement: "Pour le niveau [EsE], une revue annuelle formelle de la démarche doit être réalisée.",
    requiredForLevel: 'ESE',
    isOptional: true,
    category: 'Évaluation',
    linkedDocumentCode: 'SYNTHESE_REVUE_ANNUELLE',
    verificationMethod: 'Document de revue',
    evidence: 'PV ou synthèse de revue',
    frequency: 'Annuel',
    sortOrder: 64,
  },
  {
    chapter: 9,
    section: '9.5',
    title: 'Amélioration continue',
    description: 'Actions d\'amélioration continue',
    requirement: "L'organisation doit mettre en place des actions d'amélioration continue basées sur les évaluations.",
    requiredForLevel: 'ES',
    isOptional: false,
    category: 'Évaluation',
    verificationMethod: 'Actions documentées',
    evidence: 'Liste actions correctives',
    frequency: 'Continu',
    sortOrder: 65,
  },
];

// Chapter titles for display
export const BNQ_CHAPTER_TITLES: Record<number, string> = {
  5: 'Engagement de la direction',
  6: 'Comité santé et mieux-être',
  7: 'Collecte et analyse des données',
  8: "Plan d'action et interventions",
  9: 'Évaluation et amélioration continue',
};

// Get requirements count by chapter
export function getRequirementsByChapter(chapter: number, level: BnqLevel = 'ES'): BnqRequirementData[] {
  return BNQ_REQUIREMENTS.filter(r => {
    if (r.chapter !== chapter) return false;
    // Include requirement if it's required for the target level or lower
    const levelOrder = { ES: 1, ESE: 2, ESE_PLUS: 3 };
    return levelOrder[r.requiredForLevel] <= levelOrder[level];
  }).sort((a, b) => a.sortOrder - b.sortOrder);
}

// Get all requirements for a specific level
export function getRequirementsForLevel(level: BnqLevel): BnqRequirementData[] {
  const levelOrder = { ES: 1, ESE: 2, ESE_PLUS: 3 };
  return BNQ_REQUIREMENTS.filter(r => 
    levelOrder[r.requiredForLevel] <= levelOrder[level]
  ).sort((a, b) => a.sortOrder - b.sortOrder);
}

// Count requirements
export function countRequirements(level: BnqLevel = 'ES'): { total: number; mandatory: number; optional: number } {
  const reqs = getRequirementsForLevel(level);
  return {
    total: reqs.length,
    mandatory: reqs.filter(r => !r.isOptional).length,
    optional: reqs.filter(r => r.isOptional).length,
  };
}
