// BNQ 9700-800 Data Constants

import { BnqLevel, DocumentCategory } from '@prisma/client';

// Document types required for BNQ certification
export const BNQ_DOCUMENT_TYPES = [
  // ENGAGEMENT DIRECTION
  {
    code: 'NOTE_INTENTION',
    name: "Note d'intention / Lettre d'engagement",
    description: "Document officiel démontrant l'engagement de la direction envers la démarche santé mieux-être",
    category: 'ENGAGEMENT_DIRECTION' as DocumentCategory,
    bnqArticle: 'Art. 5.1',
    requiredForLevel: 'ES' as BnqLevel,
    isOptional: false,
    revisionFrequency: 'Si changement direction',
    sortOrder: 1,
  },
  {
    code: 'PV_APPROBATION_CA',
    name: "PV d'approbation Conseil d'Administration",
    description: "Procès-verbal de la réunion du CA approuvant la politique santé mieux-être",
    category: 'ENGAGEMENT_DIRECTION' as DocumentCategory,
    bnqArticle: 'Art. 5.2',
    requiredForLevel: 'ES' as BnqLevel,
    isOptional: false,
    revisionFrequency: 'À chaque révision politique',
    sortOrder: 2,
  },
  {
    code: 'NOMINATION_REPRESENTANT',
    name: 'Nomination représentant direction',
    description: 'Document officiel nommant le représentant de la direction pour la démarche',
    category: 'ENGAGEMENT_DIRECTION' as DocumentCategory,
    bnqArticle: 'Art. 5.5.1',
    requiredForLevel: 'ES' as BnqLevel,
    isOptional: false,
    revisionFrequency: 'Si changement',
    sortOrder: 3,
  },
  {
    code: 'NOMINATION_RESPONSABLE',
    name: 'Nomination responsable démarche',
    description: 'Document nommant le responsable opérationnel de la démarche santé mieux-être',
    category: 'ENGAGEMENT_DIRECTION' as DocumentCategory,
    bnqArticle: 'Art. 5.5.1',
    requiredForLevel: 'ES' as BnqLevel,
    isOptional: true,
    revisionFrequency: 'Si changement',
    sortOrder: 4,
  },
  // POLITIQUE & GOUVERNANCE
  {
    code: 'POLITIQUE_SME',
    name: 'Politique santé et mieux-être',
    description: 'Politique officielle de l\'entreprise en matière de santé et mieux-être au travail',
    category: 'POLITIQUE_GOUVERNANCE' as DocumentCategory,
    bnqArticle: 'Art. 5.2',
    requiredForLevel: 'ES' as BnqLevel,
    isOptional: false,
    revisionFrequency: '3 ans',
    sortOrder: 5,
  },
  {
    code: 'MANDAT_COMITE',
    name: 'Mandat et objectifs du comité',
    description: 'Document définissant le mandat, les objectifs et le fonctionnement du comité santé mieux-être',
    category: 'POLITIQUE_GOUVERNANCE' as DocumentCategory,
    bnqArticle: 'Art. 6.2',
    requiredForLevel: 'ES' as BnqLevel,
    isOptional: false,
    revisionFrequency: '3 ans',
    sortOrder: 6,
  },
  {
    code: 'LISTE_MEMBRES_COMITE',
    name: 'Liste des membres du comité',
    description: 'Liste à jour des membres du comité santé mieux-être avec leurs rôles',
    category: 'POLITIQUE_GOUVERNANCE' as DocumentCategory,
    bnqArticle: 'Art. 6.1',
    requiredForLevel: 'ES' as BnqLevel,
    isOptional: false,
    revisionFrequency: 'Annuel',
    sortOrder: 7,
  },
  {
    code: 'CR_REUNIONS_COMITE',
    name: 'Comptes-rendus réunions comité',
    description: 'Comptes-rendus des réunions du comité (minimum 4 par an)',
    category: 'POLITIQUE_GOUVERNANCE' as DocumentCategory,
    bnqArticle: 'Art. 6.2',
    requiredForLevel: 'ES' as BnqLevel,
    isOptional: false,
    revisionFrequency: 'Continu (min 4/an)',
    sortOrder: 8,
  },
  // SST & RISQUES
  {
    code: 'DUERP',
    name: 'DUERP (Document Unique d\'Evaluation des Risques)',
    description: 'Document Unique d\'Evaluation des Risques Professionnels - Obligatoire en France',
    category: 'SST_RISQUES' as DocumentCategory,
    bnqArticle: 'Art. 5.3.1',
    requiredForLevel: 'ES' as BnqLevel,
    isOptional: false,
    revisionFrequency: 'Annuel',
    sortOrder: 9,
  },
  {
    code: 'METHODE_RISQUES',
    name: "Méthode d'identification et contrôle des risques",
    description: 'Documentation de la méthode utilisée pour identifier et contrôler les risques',
    category: 'SST_RISQUES' as DocumentCategory,
    bnqArticle: 'Art. 5.3.1',
    requiredForLevel: 'ES' as BnqLevel,
    isOptional: false,
    revisionFrequency: 'Continu',
    sortOrder: 10,
  },
  {
    code: 'PROGRAMME_PREVENTION',
    name: 'Programme de prévention SST',
    description: 'Programme annuel de prévention en santé et sécurité au travail',
    category: 'SST_RISQUES' as DocumentCategory,
    bnqArticle: 'Art. 5.3',
    requiredForLevel: 'ES' as BnqLevel,
    isOptional: false,
    revisionFrequency: 'Annuel',
    sortOrder: 11,
  },
  {
    code: 'REGISTRE_ACCIDENTS',
    name: 'Registre des accidents du travail',
    description: 'Registre de suivi des accidents du travail et maladies professionnelles',
    category: 'SST_RISQUES' as DocumentCategory,
    bnqArticle: 'Art. 7.4.5.h',
    requiredForLevel: 'ESE_PLUS' as BnqLevel,
    isOptional: false,
    revisionFrequency: 'Continu',
    sortOrder: 12,
  },
  // MESURES RH
  {
    code: 'PROCEDURE_RETOUR',
    name: 'Procédure de retour au travail',
    description: 'Procédure d\'accompagnement pour le retour au travail après absence prolongée',
    category: 'MESURES_RH' as DocumentCategory,
    bnqArticle: 'Art. 5.4.a',
    requiredForLevel: 'ES' as BnqLevel,
    isOptional: false,
    revisionFrequency: '3 ans',
    sortOrder: 13,
  },
  {
    code: 'PROCEDURE_MAINTIEN',
    name: 'Procédure de maintien au travail',
    description: 'Procédure de maintien en emploi pour les personnes à capacité réduite',
    category: 'MESURES_RH' as DocumentCategory,
    bnqArticle: 'Art. 5.4.b',
    requiredForLevel: 'ESE_PLUS' as BnqLevel,
    isOptional: true,
    revisionFrequency: '3 ans',
    sortOrder: 14,
  },
  {
    code: 'DESC_TACHES_GESTIONNAIRES',
    name: 'Description tâches gestionnaires (volet santé)',
    description: 'Intégration du volet santé mieux-être dans les descriptions de tâches des gestionnaires',
    category: 'MESURES_RH' as DocumentCategory,
    bnqArticle: 'Art. 5.7',
    requiredForLevel: 'ESE' as BnqLevel,
    isOptional: true,
    revisionFrequency: 'Si modification',
    sortOrder: 15,
  },
  {
    code: 'PLAN_DEV_COMPETENCES',
    name: 'Plan développement compétences gestionnaires',
    description: 'Plan de développement des compétences des gestionnaires en santé mieux-être',
    category: 'MESURES_RH' as DocumentCategory,
    bnqArticle: 'Art. 5.7',
    requiredForLevel: 'ESE_PLUS' as BnqLevel,
    isOptional: true,
    revisionFrequency: 'Annuel',
    sortOrder: 16,
  },
  // CONFIDENTIALITE
  {
    code: 'MESURES_CONFIDENTIALITE',
    name: 'Mesures de confidentialité (écrites)',
    description: 'Document décrivant les mesures de confidentialité pour la protection des données personnelles',
    category: 'CONFIDENTIALITE' as DocumentCategory,
    bnqArticle: 'Art. 7.2',
    requiredForLevel: 'ES' as BnqLevel,
    isOptional: false,
    revisionFrequency: '3 ans',
    sortOrder: 17,
  },
  {
    code: 'CONSENTEMENT_COLLECTE',
    name: 'Formulaire de consentement collecte données',
    description: 'Formulaire de consentement éclairé pour la collecte de données personnelles',
    category: 'CONFIDENTIALITE' as DocumentCategory,
    bnqArticle: 'Art. 7.2',
    requiredForLevel: 'ES' as BnqLevel,
    isOptional: false,
    revisionFrequency: 'Par collecte',
    sortOrder: 18,
  },
  {
    code: 'POLITIQUE_DONNEES',
    name: 'Politique protection données personnelles',
    description: 'Politique RGPD/protection des données personnelles de l\'entreprise',
    category: 'CONFIDENTIALITE' as DocumentCategory,
    bnqArticle: 'Annexe B',
    requiredForLevel: 'ES' as BnqLevel,
    isOptional: false,
    revisionFrequency: '3 ans',
    sortOrder: 19,
  },
  // COLLECTE & RAPPORTS
  {
    code: 'RAPPORT_COLLECTE_PERSONNEL',
    name: 'Rapport collecte données personnel',
    description: 'Rapport de synthèse des données collectées auprès du personnel (questionnaires)',
    category: 'COLLECTE_RAPPORTS' as DocumentCategory,
    bnqArticle: 'Art. 7.5.1',
    requiredForLevel: 'ES' as BnqLevel,
    isOptional: false,
    revisionFrequency: '2-3 ans',
    sortOrder: 20,
  },
  {
    code: 'RAPPORT_DONNEES_ADMIN',
    name: 'Rapport données administratives',
    description: 'Rapport annuel des indicateurs administratifs (absentéisme, roulement, etc.)',
    category: 'COLLECTE_RAPPORTS' as DocumentCategory,
    bnqArticle: 'Art. 7.5.1',
    requiredForLevel: 'ES' as BnqLevel,
    isOptional: false,
    revisionFrequency: 'Annuel (EsE+)',
    sortOrder: 21,
  },
  {
    code: 'PLAN_ACTION_SME',
    name: "Plan d'action santé mieux-être",
    description: 'Plan d\'action annuel détaillant les interventions prévues',
    category: 'COLLECTE_RAPPORTS' as DocumentCategory,
    bnqArticle: 'Art. 8.1',
    requiredForLevel: 'ES' as BnqLevel,
    isOptional: false,
    revisionFrequency: 'Annuel',
    sortOrder: 22,
  },
  {
    code: 'RAPPORT_SYNTHESE_ANNUEL',
    name: 'Rapport synthèse annuel',
    description: 'Rapport annuel de synthèse de la démarche santé mieux-être',
    category: 'COLLECTE_RAPPORTS' as DocumentCategory,
    bnqArticle: 'Art. 9.3.2',
    requiredForLevel: 'ES' as BnqLevel,
    isOptional: false,
    revisionFrequency: 'Annuel',
    sortOrder: 23,
  },
  {
    code: 'SYNTHESE_REVUE_ANNUELLE',
    name: 'Synthèse revue annuelle démarche',
    description: 'Document de synthèse de la revue annuelle de la démarche',
    category: 'COLLECTE_RAPPORTS' as DocumentCategory,
    bnqArticle: 'Art. 9.4',
    requiredForLevel: 'ESE' as BnqLevel,
    isOptional: true,
    revisionFrequency: 'Annuel',
    sortOrder: 24,
  },
];

// Workflow steps for management adherence process
export const WORKFLOW_STEPS = [
  {
    stepNumber: 1,
    stepCode: 'ENGAGEMENT_INITIAL',
    stepName: 'Étape 1 : Engagement Initial',
    description: "Formalisation de l'engagement de la direction envers la démarche santé mieux-être",
    tasks: [
      { taskCode: 'REDACTION_NOTE', taskName: "Rédaction de la note d'intention", isRequired: true, sortOrder: 1 },
      { taskCode: 'IDENTIFICATION_REPRESENTANT', taskName: 'Identification du représentant direction', isRequired: true, sortOrder: 2 },
      { taskCode: 'COMMUNICATION_ENGAGEMENT', taskName: 'Communication de l\'engagement aux parties prenantes', isRequired: true, sortOrder: 3 },
      { taskCode: 'SIGNATURE_DG', taskName: 'Signature électronique direction générale', isRequired: true, sortOrder: 4 },
    ],
  },
  {
    stepNumber: 2,
    stepCode: 'POLITIQUE_SME',
    stepName: 'Étape 2 : Politique Santé Mieux-Être',
    description: "Rédaction, validation et communication de la politique santé mieux-être",
    tasks: [
      { taskCode: 'REDACTION_POLITIQUE', taskName: 'Rédaction de la politique (utiliser template AlterValue)', isRequired: true, sortOrder: 1 },
      { taskCode: 'VALIDATION_COMITE', taskName: 'Validation par le comité santé mieux-être', isRequired: true, sortOrder: 2 },
      { taskCode: 'APPROBATION_CA', taskName: 'Approbation CA / Direction', isRequired: true, sortOrder: 3 },
      { taskCode: 'SIGNATURE_PV', taskName: 'Signature électronique + PV approbation', isRequired: true, sortOrder: 4 },
      { taskCode: 'COMMUNICATION_PERSONNEL', taskName: 'Communication au personnel', isRequired: true, sortOrder: 5 },
      { taskCode: 'AFFICHAGE_ESE', taskName: 'Affichage (EsE)', isRequired: false, sortOrder: 6 },
    ],
  },
  {
    stepNumber: 3,
    stepCode: 'MISE_EN_PLACE_COMITE',
    stepName: 'Étape 3 : Mise en Place du Comité',
    description: 'Constitution et formalisation du comité santé mieux-être',
    tasks: [
      { taskCode: 'CONSTITUTION_COMITE', taskName: 'Constitution du comité (min 4 membres)', isRequired: true, sortOrder: 1 },
      { taskCode: 'DEFINITION_MANDAT', taskName: 'Définition du mandat et des objectifs', isRequired: true, sortOrder: 2 },
      { taskCode: 'COMMUNICATION_MEMBRES', taskName: 'Communication de la liste des membres au personnel', isRequired: true, sortOrder: 3 },
      { taskCode: 'VALIDATION_REPRESENTANT', taskName: 'Validation par le représentant direction', isRequired: true, sortOrder: 4 },
    ],
  },
  {
    stepNumber: 4,
    stepCode: 'DOCUMENTS_SST',
    stepName: 'Étape 4 : Documents SST & Risques',
    description: 'Mise à jour des documents SST et identification des risques',
    tasks: [
      { taskCode: 'MAJ_DUERP', taskName: 'DUERP à jour (obligatoire France)', isRequired: true, sortOrder: 1 },
      { taskCode: 'METHODE_RISQUES', taskName: "Méthode d'identification des risques documentée", isRequired: true, sortOrder: 2 },
      { taskCode: 'PROCEDURES_RETOUR', taskName: 'Procédures de retour/maintien au travail', isRequired: true, sortOrder: 3 },
      { taskCode: 'VALIDATION_SST', taskName: 'Validation responsable SST + direction', isRequired: true, sortOrder: 4 },
    ],
  },
  {
    stepNumber: 5,
    stepCode: 'CONFIDENTIALITE_RGPD',
    stepName: 'Étape 5 : Confidentialité & RGPD',
    description: 'Mise en place des mesures de confidentialité et conformité RGPD',
    tasks: [
      { taskCode: 'MESURES_CONFIDENTIALITE', taskName: 'Mesures de confidentialité rédigées', isRequired: true, sortOrder: 1 },
      { taskCode: 'POLITIQUE_DONNEES', taskName: 'Politique de protection des données', isRequired: true, sortOrder: 2 },
      { taskCode: 'FORMULAIRE_CONSENTEMENT', taskName: 'Formulaire de consentement collecte', isRequired: true, sortOrder: 3 },
      { taskCode: 'VALIDATION_DPO', taskName: 'Validation DPO / Direction', isRequired: true, sortOrder: 4 },
    ],
  },
];

// Category labels for display
export const CATEGORY_LABELS: Record<DocumentCategory, string> = {
  ENGAGEMENT_DIRECTION: 'Engagement Direction',
  POLITIQUE_GOUVERNANCE: 'Politique & Gouvernance',
  SST_RISQUES: 'SST & Risques',
  MESURES_RH: 'Mesures RH',
  CONFIDENTIALITE: 'Confidentialité',
  COLLECTE_RAPPORTS: 'Collecte & Rapports',
};

// BNQ Level labels
export const BNQ_LEVEL_LABELS: Record<BnqLevel, { name: string; badge: string; color: string }> = {
  ES: { name: 'Entreprise en santé', badge: '[Es]', color: 'bg-blue-500' },
  ESE: { name: 'Entreprise en santé - Élite', badge: '[EsE]', color: 'bg-purple-500' },
  ESE_PLUS: { name: 'Entreprise en santé - Élite plus', badge: '[EsE+]', color: 'bg-amber-500' },
};

// Status labels
export const STATUS_LABELS: Record<string, { label: string; color: string }> = {
  DRAFT: { label: 'Brouillon', color: 'bg-gray-500' },
  PENDING_VALIDATION: { label: 'En validation', color: 'bg-yellow-500' },
  APPROVED: { label: 'Approuvé', color: 'bg-green-500' },
  ARCHIVED: { label: 'Archivé', color: 'bg-slate-500' },
  EXPIRED: { label: 'Expiré', color: 'bg-red-500' },
};
